# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Maciej's Bits
email: maciej@gryka.net
description: > # this means to ignore newlines until "baseurl:"
  Maciej's blog and scratchbook.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maciejgryka.github.io" # the base hostname & protocol for your site
twitter_username: maciejgryka
github_username:  maciejgryka
safe: true
timezone: Europe/Berlin
encoding: utf-8
permalink: /:title

# Build settings
markdown: kramdown

# headers
webrick:
  headers:
    X-Clacks-Overhead: GNU Terry Pratchett
